import Head from "next/head";
import Header from "../components/Header";
import Display from "./../components/Display";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Garoteanteampions League</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Display />
    </div>
  );
}
